### ISSUE TITLE
windows development

### ISSUE THREAD

**Issue by oneway3124** [edgeimpulse/firmware-st-b-l475e-iot01a#2]
The development environment you use is on windows or mac?

**Comment by oneway3124** [comment]
C:\Users\19002\firmware-st-b-l475e-iot01a>mbed deploy
[mbed] Working path "C:\Users\19002\firmware-st-b-l475e-iot01a" (program)
[mbed] Adding library "BSP_B-L475E-IOT01" from "https://developer.mbed.org/teams/ST/code/BSP_B-L475E-IOT01" at rev #9dfa42666f03
[mbed] Adding library "mbed-http" from "https://os.mbed.com/teams/sandbox/code/mbed-http" at rev #a8d157986ad8
[mbed] Adding library "mbed-os" from "https://github.com/janjongboom/mbed-os" at rev #9366d8d3db62
[mbed] ERROR: Unable to clone repository (https://github.com/janjongboom/mbed-os/#9366d8d3db62528deb1d55a44fcd58997a466fa2)
---

**Comment by janjongboom** [comment]
Hi @oneway3124  interesting... Do you have git installed?

Otherwise maybe (from the `firmware-st-b-l475e-iot01a` folder):

```
git clone https://github.com/janjongboom/mbed-os
cd mbed-os
git checkout 9366d8d3db62528deb1d55a44fcd58997a466fa2
cd ..
mbed deploy
```

**Comment by oneway3124** [comment]
Thank you, I have fixed this issue.  I have used the American cloud computer for testing this mbed project code. I have completed this function.
